apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manage-resources
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: manage-resources
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ./crossplane/v1/ManagedResources
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
