apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: composition-regions-v3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: composition-regions
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ./crossplane/v3/Composition-regions
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

