apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: composition-v2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: composition
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ./crossplane/v2/Composition
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

