apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-system
spec:
  destination:
    name: ''
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.crossplane.io/master/'
    targetRevision: 1.12.0-rc.0.8.g912a9847
    chart: crossplane
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true