apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-aws
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: ./crossplane/Provider
    repoURL: 'https://github.com/itumor/demodoc.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions: []
