apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manage-resources
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: ./crossplane/v1/ManagedResources
    repoURL: 'https://github.com/itumor/demodoc.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions: []
    automated:
      prune: true
      selfHeal: true