apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
  annotations:
    argocd.argoproj.io/sync-wave: "-10"